### ISSUE TITLE
test: use openshift mongodb images

### ISSUE THREAD

**Issue by lance** [bucharest-gold/mean-booster#21]
Currently we are using an image from [bitnami](https://github.com/bucharest-gold/mean-booster/blob/master/package.json#L15). Instead we should use the one provided by openshift.

Ref: https://docs.openshift.org/latest/using_images/db_images/mongodb.html

**Comment by helio-frota** [comment]
related: https://github.com/bucharest-gold/mea5n-booster/issues/11
